name = "OwocPack"
author = "darkk1"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3aaf9af7f7f3428846c355eaee7dbc26d6fb140dd3fa66b61b65942296c52a91"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.140"
