name = "OwocPack"
author = "darkk1"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a145ac1dc4fde73397dd518686cc0cd4e97f95bc737d9a281e941a3f2169b771"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.140"
