name = "OwocPack"
author = "darkk1"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62cc036b268e27b9ed1b7a5d8a0ed2e275f79bc7add30c17aeec55a48811fff9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.140"
