name = "OwocPack"
author = "darkk1"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05ce3b172e061cf4a4a2a6e2a70daeeaeb0cd4da424657a06fca116b30d19443"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.140"
