name = "OwocPack"
author = "darkk1"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14878ceac9cda53c7a49d2bd558dcd31015c98b8708b0bbfeb2f1a98d6907276"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.140"
