name = "OwocPack"
author = "darkk1"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbafc01f64d0469fb29807f0a95183ff6edf960a231db8d5c6ccf82ef0a7d7b6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.140"
